# Generated by Django 3.1.1 on 2020-09-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_nmber',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
