# Generated by Django 3.1 on 2020-09-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20200929_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='image.png', upload_to='user_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avater',
            field=models.ImageField(default='avater.png', upload_to='avater'),
        ),
    ]
